services:
  sqlserver-db:
    build:
      context: ./docker
      dockerfile: Dockerfile.sqlserver
    container_name: alm-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AlmPrueba123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "AlmPrueba123!", "-No", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: alm-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: sqlserver-db
      DB_PORT: 1433
      DB_NAME: crud_db
      DB_USER: sa
      DB_PASSWORD: "AlmPrueba123!"
    depends_on:
      sqlserver-db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: alm-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlserver_data: